apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdk
  namespace: boring-paper-co
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sdk
  template:
    metadata:
      labels:
        app: sdk
    spec:
      containers:
      - name: sdk
        image: boringrepo.azurecr.io/boringpaperco/sdk:latest
        ports:
        - containerPort: 5000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_KEY
        - name: REGION
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REGION
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: sdk-service
  namespace: boring-paper-co
spec:
  selector:
    app: sdk
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP 