version: "3.8"

############################
#  SERVICES
############################
services:
  # ─────────── SDK API ───────────
  sdk:
    build:
      context: ./sdk
    ports:
      - "5000:5000"
    env_file:                # pull API_KEY and REGION from .env for convenience
      - .env
    environment:
      API_KEY: ${API_KEY}    # fallback if you want to override inline
      REGION:  ${REGION}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - bpc-net

  # ───────── Container XDR ────────
  containerxdr:
    build:
      context: ./containerxdr
    ports:
      - "8081:8081"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    networks:
      - bpc-net

  # ───────────── UI ───────────────
  ui:
    build:
      context: ./ui           # uses the Dockerfile we just created
    ports:
      - "8080:80"             # host:container  → browse http://localhost:8080
    depends_on:
      - sdk                   # ensure backend is up first
    environment:
      # Runtime base URL for your frontend to call the SDK API **inside** the Docker network
      # (adapt the variable name to whatever your build expects, e.g. VITE_*/REACT_APP_*)
      VITE_API_BASE_URL: http://sdk:5000
    restart: unless-stopped
    networks:
      - bpc-net

############################
#  SHARED NETWORK
############################
networks:
  bpc-net:
    driver: bridge
