apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: boring-paper-co
  labels:
    cloud-provider: gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
        cloud-provider: gcp
    spec:
      initContainers:
      - name: model-downloader
        image: ollama/ollama:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Downloading tinyllama:1.1b-chat model (smaller, faster)..."
            ollama serve &
            sleep 10
            ollama pull tinyllama:1.1b-chat
            echo "Model download complete"
            pkill ollama
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        envFrom:
        - configMapRef:
            name: app-config
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: boring-paper-co
  labels:
    cloud-provider: gcp
spec:
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434
  type: ClusterIP 