name: CI Pipeline - Build and Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  UI_CONTAINER_NAME: "ui"
  SDK_CONTAINER_NAME: "sdk"
  CONTAINERXDR_CONTAINER_NAME: "containerxdr"
  AICHAT_CONTAINER_NAME: "aichat"
  RELEASE: "latest"

jobs:
  UI:
    runs-on: ubuntu-latest
    name: UI Build and Scan
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${{ env.UI_CONTAINER_NAME }}:${{ env.RELEASE }} ui/
      - name: Install TMAS CLI
        run: |
          curl -f -s -o tmas-cli.tar.gz "https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz"
          tar -xzf tmas-cli.tar.gz
          sudo mv ./tmas /usr/local/bin/tmas
      - name: Scan with TMAS
        run: |
          export TMAS_API_KEY='${{ secrets.V1_API_KEY }}'
          docker save "${UI_CONTAINER_NAME}:${RELEASE}" > image.tar
          tmas scan "docker-archive:image.tar" -VMS

  SDK:
    runs-on: ubuntu-latest
    name: SDK Build and Scan
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${{ env.SDK_CONTAINER_NAME }}:${{ env.RELEASE }} sdk/
      - name: Install TMAS CLI
        run: |
          curl -f -s -o tmas-cli.tar.gz "https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz"
          tar -xzf tmas-cli.tar.gz
          sudo mv ./tmas /usr/local/bin/tmas
      - name: Scan with TMAS
        run: |
          export TMAS_API_KEY='${{ secrets.V1_API_KEY }}'
          docker save "${SDK_CONTAINER_NAME}:${RELEASE}" > image.tar
          tmas scan "docker-archive:image.tar" -VMS

  ContainerXDR:
    runs-on: ubuntu-latest
    name: ContainerXDR Build and Scan
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${{ env.CONTAINERXDR_CONTAINER_NAME }}:${{ env.RELEASE }} containerxdr/
      - name: Install TMAS CLI
        run: |
          curl -f -s -o tmas-cli.tar.gz "https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz"
          tar -xzf tmas-cli.tar.gz
          sudo mv ./tmas /usr/local/bin/tmas
      - name: Scan with TMAS
        run: |
          export TMAS_API_KEY='${{ secrets.V1_API_KEY }}'
          docker save "${CONTAINERXDR_CONTAINER_NAME}:${RELEASE}" > image.tar
          tmas scan "docker-archive:image.tar" -VMS

  AIChat:
    runs-on: ubuntu-latest
    name: AI Chat Build and Scan
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${{ env.AICHAT_CONTAINER_NAME }}:${{ env.RELEASE }} aichat/
      - name: Install TMAS CLI
        run: |
          curl -f -s -o tmas-cli.tar.gz "https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz"
          tar -xzf tmas-cli.tar.gz
          sudo mv ./tmas /usr/local/bin/tmas
      - name: Scan with TMAS
        run: |
          export TMAS_API_KEY='${{ secrets.V1_API_KEY }}'
          docker save "${AICHAT_CONTAINER_NAME}:${RELEASE}" > image.tar
          tmas scan "docker-archive:image.tar" -VMS
